apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipedata
  labels:
    type: local
    app: recipedata
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: recipedata
data:
  POSTGRES_DB: "recipe-db"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_USER: "admin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipedata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipedata
  template:
    metadata:
      labels:
        app: recipedata
    spec:
      containers:
        - name: recipe-db
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: recipedata
      volumes:
        - name: recipedata
          persistentVolumeClaim:
            claimName: recipe-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: recipe-db
  labels:
    app: recipedata
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: recipedata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-volume-claim
  labels:
    app: recipedata
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi