name: Workflow (Production)

on:
  push:
    branches:
      - 'main'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  build_and_push_docker:
   runs-on: ubuntu-latest
   needs: qodana
   steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: innaxn/foody-recipe-service:production-latest
  # deploy_to_aks:
  #   runs-on: ubuntu-latest
  #   needs: build_and_push_docker
  #   steps:
  #     - name: Checkout source code 
  #       uses: actions/checkout@v3

  #     - name: Azure login
  #       id: login
  #       uses: azure/login@v1.4.3
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Set AKS context
  #       id: set-context
  #       uses: azure/aks-set-context@v3
  #       with:
  #         resource-group: '${{ secrets.resource_group }}' 
  #         cluster-name: '${{ secrets.cluster_name }}'

  #     - name: Setup kubectl
  #       id: install-kubectl
  #       uses: azure/setup-kubectl@v3

  #     - name: Deploy to AKS
  #       id: deploy-aks
  #       uses: Azure/k8s-deploy@v4
  #       with:
  #         namespace: 'default'
  #         manifests: |
  #           prod.deployment.yaml
  #         images: innaxn/foody-recipe-service:production-latest
  #         pull-images: true
